defaults:
  - _self_
  - env: dflex_ant
  - alg: pwm

horizon: 16

general:
  train: True
  logdir: logs
  render: False # rendering is computationally expensive
  device: cuda:0
  run_wandb: False
  seed: 42
  checkpoint: # model checkpoint to load
  checkpoint_with_buffer: False # whether to load buffer too
  resume_training: False # whether to resume training from checkpoint (restores epoch, step count, etc.)
  eval_runs: 12 # number of env evals to do at end of training
  pretrain: # if provided, will pretrain model on this data before running environment
  pretrain_steps: 50000 # how many gradient steps to pretrain for

wandb:
  project: 
  entity: 
  group: 
  notes: ""
